added support for all the other metadata fields, and embedded art

diff --git a/flac2alac b/flac2alac
--- a/flac2alac
+++ b/flac2alac
@@ -1,24 +1,81 @@
 #!/bin/sh
 
-echo ""
-echo "flac2alac - script to convert FLAC audio to ALAC"
-echo "By Arlindo \"Nighto\" Pereira"
-echo "<nighto@nighto.net>"
-echo "(C) 2010. Licensed on GPLv3"
-echo ""
+# flac2alac By Arlindo \"Nighto\" Pereira <nighto@nighto.net>
+# (C) 2010. Licensed on GPLv3"
 
-if [ "$1" ]
-then
-	ffmpeg  -i "$1" -acodec alac "`basename "$1" .flac`.m4a" \
-		-metadata title=\""$(metaflac --show-tag=TITLE "$1" | sed 's/TITLE=//g' | sed 's/title=//g')"\" \
-		-metadata author=\""$(metaflac --show-tag=ARTIST "$1" | sed 's/ARTIST=//g' | sed 's/artist=//g')"\" \
-		-metadata album=\""$(metaflac --show-tag=ALBUM "$1" | sed 's/ALBUM=//g' | sed 's/album=//g')"\" \
-		-metadata year=\""$(metaflac --show-tag=DATE "$1" | sed 's/DATE=//g' | sed 's/date=//g')"\" \
-		-metadata track=\""$(metaflac --show-tag=TRACKNUMBER "$1" | sed 's/TRACKNUMBER=//g' | sed 's/tracknumber=//g')"\" \
-		-metadata genre=\""$(metaflac --show-tag=GENRE "$1" | sed 's/GENRE=//g' | sed 's/genre=//g')"\"
-else
-	echo "Usage:"
-	echo "flac2alac file.flac"
-	echo ""
-exit 1
+# modified by jeffrey paul <sneak@datavibe.net>
+
+# this requires ImageMagick (for convert), mpeg4ip (for mp4tags),
+# recent flac (for metaflac with --export-picture-to), and
+# ffmpeg with alac (apple lossless) and flac support built in
+
+
+function _convert_flac2alac {
+	NF="`basename \"$1\" .flac`.m4a"
+	D="`dirname \"$1\"`"
+
+	ARTIST="`metaflac --show-tag=ARTIST \"$1\" | sed s/ARTIST=//g`"
+	ALBUMARTIST="`metaflac --show-tag=ALBUMARTIST \"$1\" | sed s/ALBUMARTIST=//g`"
+	TITLE="`metaflac --show-tag=TITLE \"$1\" | sed s/TITLE=//g`"
+	ALBUM="`metaflac --show-tag=ALBUM \"$1\" | sed s/ALBUM=//g`"
+	DATE="`metaflac --show-tag=DATE \"$1\" | sed s/DATE=//g`"
+	GENRE="`metaflac --show-tag=GENRE \"$1\" | sed s/GENRE=//g`"
+	TRACKNUMBER="`metaflac --show-tag=TRACKNUMBER \"$1\" | sed s/TRACKNUMBER=//g`"
+	TRACKTOTAL="`metaflac --show-tag=TRACKTOTAL \"$1\" | sed s/TRACKTOTAL=//g`"
+	DISCNUMBER="`metaflac --show-tag=DISCNUMBER \"$1\" | sed s/DISCNUMBER=//g`"
+	DISCTOTAL="`metaflac --show-tag=DISCTOTAL \"$1\" | sed s/DISCTOTAL=//g`"
+	DESCRIPTION="`metaflac --show-tag=DESCRIPTION \"$1\" | sed s/DESCRIPTION=//g`"
+	COMPOSER="`metaflac --show-tag=COMPOSER \"$1\" | sed s/COMPOSER=//g`"
+	ARTFORMAT="`metaflac --export-picture-to=- \"$1\" | file -i -b -`"
+	ARTFILE=".arttmp.${NF}"
+
+	if [ "$ARTFORMAT" != "application/x-empty" ]; then
+		metaflac --export-picture-to="${D}/${ARTFILE}" "$1"
+		if [ "$ARTFORMAT" = "image/png" ]; then ARTEXT="png"; fi
+		if [ "$ARTFORMAT" = "image/jpeg" ]; then ARTEXT="jpg"; fi
+		if [ -z "$ARTEXT" ]; then
+			echo "unknown embedded album art format ${ARTFORMAT}, cannot continue." > /dev/stderr
+			exit 1;
+		fi
+	fi
+
+	ffmpeg -v -1 -i "$1" -acodec alac "${D}/.tmp.${NF}" 
+
+	if [ $? -ne 0 ]; then
+		echo "Problem running conversion, exiting." > /dev/stderr
+		rm -f "${D}/.tmp.${NF}" "${D}/${ARTFILE}"
+		exit 1
+	fi
+
+	mp4tags -s "$TITLE" "${D}/.tmp.${NF}"
+	mp4tags -t "$TRACKNUMBER" "${D}/.tmp.${NF}"
+	mp4tags -T "$TRACKTOTAL" "${D}/.tmp.${NF}"
+	mp4tags -d "$DISCNUMBER" "${D}/.tmp.${NF}"
+	mp4tags -D "$DISCTOTAL" "${D}/.tmp.${NF}"
+	mp4tags -w "$COMPOSER" "${D}/.tmp.${NF}"
+	mp4tags -c "$DESCRIPTION" "${D}/.tmp.${NF}"
+	mp4tags -a "$ARTIST" "${D}/.tmp.${NF}"
+	mp4tags -R "$ALBUMARTIST" "${D}/.tmp.${NF}"
+	mp4tags -A "$ALBUM" "${D}/.tmp.${NF}"
+	mp4tags -g "$GENRE" "${D}/.tmp.${NF}" 
+	mp4tags -y "$DATE"  "${D}/.tmp.${NF}"
+
+	if [ -f "${D}/$ARTFILE" ]; then
+		# this embeds a png or jpeg cover into the m4a if it was
+		# found in the original flac file
+		mp4tags -P "${D}/$ARTFILE" "${D}/.tmp.${NF}"
+		rm -f "${D}/${ARTFILE}"	
+	fi
+
+	mv "${D}/.tmp.${NF}" "${D}/${NF}"
+}
+
+if [ ! -f "$1" ]; then
+	echo "usage: $0 <file.flac> [file2.flac] [...]" > /dev/stderr
+	exit 1
 fi
+
+for filename in "$@"; do
+	_convert_flac2alac "$filename"
+done
+
